#!/bin/bash

#RUBY

#Acquire the list of ruby-related packages
ruby1_packages=`sudo aptitude search ruby | grep '^i' | awk '{print $2}' | grep -v '^A'`
ruby2_packages=`sudo aptitude search ruby | grep '^i' | awk '{print $3}' | grep -v '^\-'`
ruby_packages_final=`echo "$ruby1_packages $ruby2_packages"`

#Put the ruby packages on hold
for package in $ruby_packages_final; do
	sudo apt-mark hold $package
	done

#MYSQL
mysql1_packages=`sudo aptitude search mysql | grep '^i' | awk '{print $2}' | grep -v '^A'`
mysql2_packages=`sudo aptitude search mysql | grep '^i' | awk '{print $3}' | grep -v '^\-'`
mysql_packages_final=`echo "$mysql1_packages $mysql2_packages"`

#Put the mysql packages on hold
for package in $mysql_packages_final; do
	sudo apt-mark hold $package
	done

#Update the sources list
sudo apt-get update

#Update the system
sudo apt-get upgrade
